# Generated by Django 5.2.6 on 2025-10-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("image", models.FileField(upload_to="media_files/")),
            ],
        ),
    ]
