# Generated by Django 5.2.6 on 2025-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
