# Generated by Django 5.2.6 on 2025-11-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField()),
                ("duration", models.CharField(max_length=50)),
                ("course_name", models.CharField(max_length=200)),
                ("course_price", models.FloatField()),
                ("students_enrolled", models.IntegerField()),
                ("course_image", models.ImageField(upload_to="course_images/")),
                ("instructor_name", models.CharField(max_length=100)),
            ],
        ),
    ]
