# Generated by Django 5.2.6 on 2025-11-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instructors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructor_name", models.CharField(max_length=100)),
                ("instructor_designation", models.CharField(max_length=100)),
                ("instructor_image", models.ImageField(upload_to="instructor_images/")),
            ],
        ),
    ]
